use std::fmt;

#[allow(non_camel_case_types)]
#[derive(PartialEq, Debug, Clone)]
pub enum SyntaxTokenType {
    // Keywords
    AppendStructuredBufferKeyword,
    BlendStateKeyword,
    BoolKeyword,
    Bool1Keyword,
    Bool2Keyword,
    Bool3Keyword,
    Bool4Keyword,
    Bool1x1Keyword,
    Bool1x2Keyword,
    Bool1x3Keyword,
    Bool1x4Keyword,
    Bool2x1Keyword,
    Bool2x2Keyword,
    Bool2x3Keyword,
    Bool2x4Keyword,
    Bool3x1Keyword,
    Bool3x2Keyword,
    Bool3x3Keyword,
    Bool3x4Keyword,
    Bool4x1Keyword,
    Bool4x2Keyword,
    Bool4x3Keyword,
    Bool4x4Keyword,
    BufferKeyword,
    ByteAddressBufferKeyword,
    BreakKeyword,
    CaseKeyword,
    CBufferKeyword,
    CentroidKeyword,
    ClassKeyword,
    ColumnMajorKeyword,
    CompileKeyword,
    CompileShaderKeyword,
    ConstantBufferKeyword,
    ConstKeyword,
    ConsumeStructuredBufferKeyword,
    ContinueKeyword,
    DefaultKeyword,
    DefKeyword,
    DepthStencilStateKeyword,
    DiscardKeyword,
    DoKeyword,
    DoubleKeyword,
    Double1Keyword,
    Double2Keyword,
    Double3Keyword,
    Double4Keyword,
    Double1x1Keyword,
    Double1x2Keyword,
    Double1x3Keyword,
    Double1x4Keyword,
    Double2x1Keyword,
    Double2x2Keyword,
    Double2x3Keyword,
    Double2x4Keyword,
    Double3x1Keyword,
    Double3x2Keyword,
    Double3x3Keyword,
    Double3x4Keyword,
    Double4x1Keyword,
    Double4x2Keyword,
    Double4x3Keyword,
    Double4x4Keyword,
    ElseKeyword,
    ErrorKeyword,
    ExportKeyword,
    ExternKeyword,
    FloatKeyword,
    Float1Keyword,
    Float2Keyword,
    Float3Keyword,
    Float4Keyword,
    Float1x1Keyword,
    Float1x2Keyword,
    Float1x3Keyword,
    Float1x4Keyword,
    Float2x1Keyword,
    Float2x2Keyword,
    Float2x3Keyword,
    Float2x4Keyword,
    Float3x1Keyword,
    Float3x2Keyword,
    Float3x3Keyword,
    Float3x4Keyword,
    Float4x1Keyword,
    Float4x2Keyword,
    Float4x3Keyword,
    Float4x4Keyword,
    ForKeyword,
    GeometryShaderKeyword,
    GloballycoherentKeyword,
    GroupsharedKeyword,
    HalfKeyword,
    Half1Keyword,
    Half2Keyword,
    Half3Keyword,
    Half4Keyword,
    Half1x1Keyword,
    Half1x2Keyword,
    Half1x3Keyword,
    Half1x4Keyword,
    Half2x1Keyword,
    Half2x2Keyword,
    Half2x3Keyword,
    Half2x4Keyword,
    Half3x1Keyword,
    Half3x2Keyword,
    Half3x3Keyword,
    Half3x4Keyword,
    Half4x1Keyword,
    Half4x2Keyword,
    Half4x3Keyword,
    Half4x4Keyword,
    Float16_tKeyword,
    Float16_t1Keyword,
    Float16_t2Keyword,
    Float16_t3Keyword,
    Float16_t4Keyword,
    Float16_t1x1Keyword,
    Float16_t1x2Keyword,
    Float16_t1x3Keyword,
    Float16_t1x4Keyword,
    Float16_t2x1Keyword,
    Float16_t2x2Keyword,
    Float16_t2x3Keyword,
    Float16_t2x4Keyword,
    Float16_t3x1Keyword,
    Float16_t3x2Keyword,
    Float16_t3x3Keyword,
    Float16_t3x4Keyword,
    Float16_t4x1Keyword,
    Float16_t4x2Keyword,
    Float16_t4x3Keyword,
    Float16_t4x4Keyword,
    IfKeyword,
    IndicesKeyword,
    InKeyword,
    InlineKeyword,
    InoutKeyword,
    InputPatchKeyword,
    IntKeyword,
    Int1Keyword,
    Int2Keyword,
    Int3Keyword,
    Int4Keyword,
    Int1x1Keyword,
    Int1x2Keyword,
    Int1x3Keyword,
    Int1x4Keyword,
    Int2x1Keyword,
    Int2x2Keyword,
    Int2x3Keyword,
    Int2x4Keyword,
    Int3x1Keyword,
    Int3x2Keyword,
    Int3x3Keyword,
    Int3x4Keyword,
    Int4x1Keyword,
    Int4x2Keyword,
    Int4x3Keyword,
    Int4x4Keyword,
    Int64_tKeyword,
    Int64_t1Keyword,
    Int64_t2Keyword,
    Int64_t3Keyword,
    Int64_t4Keyword,
    Int64_t1x1Keyword,
    Int64_t1x2Keyword,
    Int64_t1x3Keyword,
    Int64_t1x4Keyword,
    Int64_t2x1Keyword,
    Int64_t2x2Keyword,
    Int64_t2x3Keyword,
    Int64_t2x4Keyword,
    Int64_t3x1Keyword,
    Int64_t3x2Keyword,
    Int64_t3x3Keyword,
    Int64_t3x4Keyword,
    Int64_t4x1Keyword,
    Int64_t4x2Keyword,
    Int64_t4x3Keyword,
    Int64_t4x4Keyword,
    Int16_tKeyword,
    Int16_t1Keyword,
    Int16_t2Keyword,
    Int16_t3Keyword,
    Int16_t4Keyword,
    Int16_t1x1Keyword,
    Int16_t1x2Keyword,
    Int16_t1x3Keyword,
    Int16_t1x4Keyword,
    Int16_t2x1Keyword,
    Int16_t2x2Keyword,
    Int16_t2x3Keyword,
    Int16_t2x4Keyword,
    Int16_t3x1Keyword,
    Int16_t3x2Keyword,
    Int16_t3x3Keyword,
    Int16_t3x4Keyword,
    Int16_t4x1Keyword,
    Int16_t4x2Keyword,
    Int16_t4x3Keyword,
    Int16_t4x4Keyword,
    InterfaceKeyword,
    LineKeyword,
    LineAdjKeyword,
    LinearKeyword,
    LineStreamKeyword,
    MatrixKeyword,
    MessageKeyword,
    Min10FloatKeyword,
    Min10Float1Keyword,
    Min10Float2Keyword,
    Min10Float3Keyword,
    Min10Float4Keyword,
    Min10Float1x1Keyword,
    Min10Float1x2Keyword,
    Min10Float1x3Keyword,
    Min10Float1x4Keyword,
    Min10Float2x1Keyword,
    Min10Float2x2Keyword,
    Min10Float2x3Keyword,
    Min10Float2x4Keyword,
    Min10Float3x1Keyword,
    Min10Float3x2Keyword,
    Min10Float3x3Keyword,
    Min10Float3x4Keyword,
    Min10Float4x1Keyword,
    Min10Float4x2Keyword,
    Min10Float4x3Keyword,
    Min10Float4x4Keyword,
    Min12IntKeyword,
    Min12Int1Keyword,
    Min12Int2Keyword,
    Min12Int3Keyword,
    Min12Int4Keyword,
    Min12Int1x1Keyword,
    Min12Int1x2Keyword,
    Min12Int1x3Keyword,
    Min12Int1x4Keyword,
    Min12Int2x1Keyword,
    Min12Int2x2Keyword,
    Min12Int2x3Keyword,
    Min12Int2x4Keyword,
    Min12Int3x1Keyword,
    Min12Int3x2Keyword,
    Min12Int3x3Keyword,
    Min12Int3x4Keyword,
    Min12Int4x1Keyword,
    Min12Int4x2Keyword,
    Min12Int4x3Keyword,
    Min12Int4x4Keyword,
    Min16FloatKeyword,
    Min16Float1Keyword,
    Min16Float2Keyword,
    Min16Float3Keyword,
    Min16Float4Keyword,
    Min16Float1x1Keyword,
    Min16Float1x2Keyword,
    Min16Float1x3Keyword,
    Min16Float1x4Keyword,
    Min16Float2x1Keyword,
    Min16Float2x2Keyword,
    Min16Float2x3Keyword,
    Min16Float2x4Keyword,
    Min16Float3x1Keyword,
    Min16Float3x2Keyword,
    Min16Float3x3Keyword,
    Min16Float3x4Keyword,
    Min16Float4x1Keyword,
    Min16Float4x2Keyword,
    Min16Float4x3Keyword,
    Min16Float4x4Keyword,
    Min16IntKeyword,
    Min16Int1Keyword,
    Min16Int2Keyword,
    Min16Int3Keyword,
    Min16Int4Keyword,
    Min16Int1x1Keyword,
    Min16Int1x2Keyword,
    Min16Int1x3Keyword,
    Min16Int1x4Keyword,
    Min16Int2x1Keyword,
    Min16Int2x2Keyword,
    Min16Int2x3Keyword,
    Min16Int2x4Keyword,
    Min16Int3x1Keyword,
    Min16Int3x2Keyword,
    Min16Int3x3Keyword,
    Min16Int3x4Keyword,
    Min16Int4x1Keyword,
    Min16Int4x2Keyword,
    Min16Int4x3Keyword,
    Min16Int4x4Keyword,
    Min16UintKeyword,
    Min16Uint1Keyword,
    Min16Uint2Keyword,
    Min16Uint3Keyword,
    Min16Uint4Keyword,
    Min16Uint1x1Keyword,
    Min16Uint1x2Keyword,
    Min16Uint1x3Keyword,
    Min16Uint1x4Keyword,
    Min16Uint2x1Keyword,
    Min16Uint2x2Keyword,
    Min16Uint2x3Keyword,
    Min16Uint2x4Keyword,
    Min16Uint3x1Keyword,
    Min16Uint3x2Keyword,
    Min16Uint3x3Keyword,
    Min16Uint3x4Keyword,
    Min16Uint4x1Keyword,
    Min16Uint4x2Keyword,
    Min16Uint4x3Keyword,
    Min16Uint4x4Keyword,
    NamespaceKeyword,
    NointerpolationKeyword,
    NoperspectiveKeyword,
    NullKeyword,
    OutKeyword,
    OutputPatchKeyword,
    PackMatrixKeyword,
    PackoffsetKeyword,
    PassKeyword,
    PayloadKeyword,
    PixelShaderKeyword,
    PointKeyword,
    PointStreamKeyword,
    PreciseKeyword,
    PrimitivesKeyword,
    RasterizerOrderedBufferKeyword,
    RasterizerOrderedByteAddressBufferKeyword,
    RasterizerOrderedStructuredBufferKeyword,
    RasterizerOrderedTexture1DKeyword,
    RasterizerOrderedTexture1DArrayKeyword,
    RasterizerOrderedTexture2DKeyword,
    RasterizerOrderedTexture2DArrayKeyword,
    RasterizerOrderedTexture3DKeyword,
    RasterizerStateKeyword,
    RegisterKeyword,
    ReturnKeyword,
    RowMajorKeyword,
    RWBufferKeyword,
    RWByteAddressBufferKeyword,
    RWStructuredBufferKeyword,
    RWTexture1DKeyword,
    RWTexture1DArrayKeyword,
    RWTexture2DKeyword,
    RWTexture2DArrayKeyword,
    RWTexture3DKeyword,
    SampleKeyword,
    SamplerKeyword,
    Sampler1DKeyword,
    Sampler2DKeyword,
    Sampler3DKeyword,
    SamplerCubeKeyword,
    SamplerComparisonStateKeyword,
    SamplerStateKeyword,
    SamplerStateLegacyKeyword,
    SharedKeyword,
    SNormKeyword,
    StaticKeyword,
    StringKeyword,
    StructKeyword,
    StructuredBufferKeyword,
    SwitchKeyword,
    TBufferKeyword,
    TechniqueKeyword,
    Technique10Keyword,
    Technique11Keyword,
    TextureKeyword,
    Texture2DLegacyKeyword,
    TextureCubeLegacyKeyword,
    Texture1DKeyword,
    Texture1DArrayKeyword,
    Texture2DKeyword,
    Texture2DArrayKeyword,
    Texture2DMSKeyword,
    Texture2DMSArrayKeyword,
    Texture3DKeyword,
    TextureCubeKeyword,
    TextureCubeArrayKeyword,
    TriangleKeyword,
    TriangleAdjKeyword,
    TriangleStreamKeyword,
    TypedefKeyword,
    UniformKeyword,
    UNormKeyword,
    UintKeyword,
    Uint1Keyword,
    Uint2Keyword,
    Uint3Keyword,
    Uint4Keyword,
    Uint1x1Keyword,
    Uint1x2Keyword,
    Uint1x3Keyword,
    Uint1x4Keyword,
    Uint2x1Keyword,
    Uint2x2Keyword,
    Uint2x3Keyword,
    Uint2x4Keyword,
    Uint3x1Keyword,
    Uint3x2Keyword,
    Uint3x3Keyword,
    Uint3x4Keyword,
    Uint4x1Keyword,
    Uint4x2Keyword,
    Uint4x3Keyword,
    Uint4x4Keyword,
    Uint64_tKeyword,
    Uint64_t1Keyword,
    Uint64_t2Keyword,
    Uint64_t3Keyword,
    Uint64_t4Keyword,
    Uint64_t1x1Keyword,
    Uint64_t1x2Keyword,
    Uint64_t1x3Keyword,
    Uint64_t1x4Keyword,
    Uint64_t2x1Keyword,
    Uint64_t2x2Keyword,
    Uint64_t2x3Keyword,
    Uint64_t2x4Keyword,
    Uint64_t3x1Keyword,
    Uint64_t3x2Keyword,
    Uint64_t3x3Keyword,
    Uint64_t3x4Keyword,
    Uint64_t4x1Keyword,
    Uint64_t4x2Keyword,
    Uint64_t4x3Keyword,
    Uint64_t4x4Keyword,
    Uint16_tKeyword,
    Uint16_t1Keyword,
    Uint16_t2Keyword,
    Uint16_t3Keyword,
    Uint16_t4Keyword,
    Uint16_t1x1Keyword,
    Uint16_t1x2Keyword,
    Uint16_t1x3Keyword,
    Uint16_t1x4Keyword,
    Uint16_t2x1Keyword,
    Uint16_t2x2Keyword,
    Uint16_t2x3Keyword,
    Uint16_t2x4Keyword,
    Uint16_t3x1Keyword,
    Uint16_t3x2Keyword,
    Uint16_t3x3Keyword,
    Uint16_t3x4Keyword,
    Uint16_t4x1Keyword,
    Uint16_t4x2Keyword,
    Uint16_t4x3Keyword,
    Uint16_t4x4Keyword,
    VectorKeyword,
    VertexShaderKeyword,
    VerticesKeyword,
    VolatileKeyword,
    VoidKeyword,
    WarningKeyword,
    WhileKeyword,

    TrueKeyword,
    FalseKeyword,

    // Tokens
    OpenParenToken,
    CloseParenToken,
    OpenBracketToken,
    CloseBracketToken,
    OpenBraceToken,
    CloseBraceToken,

    SemiToken,
    CommaToken,

    LessThanToken,
    LessThanEqualsToken,
    GreaterThanToken,
    GreaterThanEqualsToken,
    LessThanLessThanToken,
    GreaterThanGreaterThanToken,
    PlusToken,
    PlusPlusToken,
    MinusToken,
    MinusMinusToken,
    AsteriskToken,
    SlashToken,
    PercentToken,
    AmpersandToken,
    BarToken,
    AmpersandAmpersandToken,
    BarBarToken,
    CaretToken,
    NotToken,
    TildeToken,
    QuestionToken,
    ColonToken,
    ColonColonToken,

    EqualsToken,
    AsteriskEqualsToken,
    SlashEqualsToken,
    PercentEqualsToken,
    PlusEqualsToken,
    MinusEqualsToken,
    LessThanLessThanEqualsToken,
    GreaterThanGreaterThanEqualsToken,
    AmpersandEqualsToken,
    CaretEqualsToken,
    BarEqualsToken,

    EqualsEqualsToken,
    ExclamationEqualsToken,
    DotToken,
    HashToken,
    HashHashToken,

    UnsignedKeyword,
    DwordKeyword,

    IdentifierToken,
    IntegerLiteralToken { value: i128 }, // use more bits here to support u64
    FloatLiteralToken { value: f64 },
    CharacterLiteralToken { value: char },
    StringLiteralToken { value: String },
    BracketedStringLiteralToken,
    PreprocessingNumber,

    EndOfFileToken,

    IfDirective,
    IfDefDirective,
    IfNDefDirective,
    ElifDirective,
    ElseDirective,
    EndIfDirective,
    PragmaDirective {
        value: String,
    },
    ErrorDirective {
        value: String
    },
    LineDirective {
        value: String
    },
    IncludeDirective {
        path: String,
    },
    PreProcessorDefinition {
        name: String,
        value: String,
    },
    PreProcessorDefinitionFunction {
        name: String,
        args: String,
        value: String,
    },
    UndefDirective {
        name: String,
    },
    BadDirective {
        name: String
    },

    WhiteSpace,
    BadToken,
}

impl Default for SyntaxTokenType {
    fn default() -> Self {
        return Self::BadToken;
    }
}

impl fmt::Display for SyntaxTokenType
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

pub fn get_keyword_token_type(text: &String) -> SyntaxTokenType {
    match text.as_str() {
        "AppendStructuredBuffer" => SyntaxTokenType::AppendStructuredBufferKeyword,
        "BlendState" => SyntaxTokenType::BlendStateKeyword,
        "bool" => SyntaxTokenType::BoolKeyword,
        "bool1" => SyntaxTokenType::Bool1Keyword,
        "bool2" => SyntaxTokenType::Bool2Keyword,
        "bool3" => SyntaxTokenType::Bool3Keyword,
        "bool4" => SyntaxTokenType::Bool4Keyword,
        "bool1x1" => SyntaxTokenType::Bool1x1Keyword,
        "bool1x2" => SyntaxTokenType::Bool1x2Keyword,
        "bool1x3" => SyntaxTokenType::Bool1x3Keyword,
        "bool1x4" => SyntaxTokenType::Bool1x4Keyword,
        "bool2x1" => SyntaxTokenType::Bool2x1Keyword,
        "bool2x2" => SyntaxTokenType::Bool2x2Keyword,
        "bool2x3" => SyntaxTokenType::Bool2x3Keyword,
        "bool2x4" => SyntaxTokenType::Bool2x4Keyword,
        "bool3x1" => SyntaxTokenType::Bool3x1Keyword,
        "bool3x2" => SyntaxTokenType::Bool3x2Keyword,
        "bool3x3" => SyntaxTokenType::Bool3x3Keyword,
        "bool3x4" => SyntaxTokenType::Bool3x4Keyword,
        "bool4x1" => SyntaxTokenType::Bool4x1Keyword,
        "bool4x2" => SyntaxTokenType::Bool4x2Keyword,
        "bool4x3" => SyntaxTokenType::Bool4x3Keyword,
        "bool4x4" => SyntaxTokenType::Bool4x4Keyword,
        "Buffer" => SyntaxTokenType::BufferKeyword,
        "ByteAddressBuffer" => SyntaxTokenType::ByteAddressBufferKeyword,
        "break" => SyntaxTokenType::BreakKeyword,
        "case" => SyntaxTokenType::CaseKeyword,
        "cbuffer" => SyntaxTokenType::CBufferKeyword,
        "centroid" => SyntaxTokenType::CentroidKeyword,
        "class" => SyntaxTokenType::ClassKeyword,
        "column_major" => SyntaxTokenType::ColumnMajorKeyword,
        "compile" => SyntaxTokenType::CompileKeyword,
        "const" => SyntaxTokenType::ConstKeyword,
        "ConsumeStructuredBuffer" => SyntaxTokenType::ConsumeStructuredBufferKeyword,
        "continue" => SyntaxTokenType::ContinueKeyword,
        "default" => SyntaxTokenType::DefaultKeyword,
        "DepthStencilState" => SyntaxTokenType::DepthStencilStateKeyword,
        "discard" => SyntaxTokenType::DiscardKeyword,
        "do" => SyntaxTokenType::DoKeyword,
        "double" => SyntaxTokenType::DoubleKeyword,
        "double1" => SyntaxTokenType::Double1Keyword,
        "double2" => SyntaxTokenType::Double2Keyword,
        "double3" => SyntaxTokenType::Double3Keyword,
        "double4" => SyntaxTokenType::Double4Keyword,
        "double1x1" => SyntaxTokenType::Double1x1Keyword,
        "double1x2" => SyntaxTokenType::Double1x2Keyword,
        "double1x3" => SyntaxTokenType::Double1x3Keyword,
        "double1x4" => SyntaxTokenType::Double1x4Keyword,
        "double2x1" => SyntaxTokenType::Double2x1Keyword,
        "double2x2" => SyntaxTokenType::Double2x2Keyword,
        "double2x3" => SyntaxTokenType::Double2x3Keyword,
        "double2x4" => SyntaxTokenType::Double2x4Keyword,
        "double3x1" => SyntaxTokenType::Double3x1Keyword,
        "double3x2" => SyntaxTokenType::Double3x2Keyword,
        "double3x3" => SyntaxTokenType::Double3x3Keyword,
        "double3x4" => SyntaxTokenType::Double3x4Keyword,
        "double4x1" => SyntaxTokenType::Double4x1Keyword,
        "double4x2" => SyntaxTokenType::Double4x2Keyword,
        "double4x3" => SyntaxTokenType::Double4x3Keyword,
        "double4x4" => SyntaxTokenType::Double4x4Keyword,
        "else" => SyntaxTokenType::ElseKeyword,
        "export" => SyntaxTokenType::ExportKeyword,
        "extern" => SyntaxTokenType::ExternKeyword,
        "float" => SyntaxTokenType::FloatKeyword,
        "float1" => SyntaxTokenType::Float1Keyword,
        "float2" => SyntaxTokenType::Float2Keyword,
        "float3" => SyntaxTokenType::Float3Keyword,
        "float4" => SyntaxTokenType::Float4Keyword,
        "float1x1" => SyntaxTokenType::Float1x1Keyword,
        "float1x2" => SyntaxTokenType::Float1x2Keyword,
        "float1x3" => SyntaxTokenType::Float1x3Keyword,
        "float1x4" => SyntaxTokenType::Float1x4Keyword,
        "float2x1" => SyntaxTokenType::Float2x1Keyword,
        "float2x2" => SyntaxTokenType::Float2x2Keyword,
        "float2x3" => SyntaxTokenType::Float2x3Keyword,
        "float2x4" => SyntaxTokenType::Float2x4Keyword,
        "float3x1" => SyntaxTokenType::Float3x1Keyword,
        "float3x2" => SyntaxTokenType::Float3x2Keyword,
        "float3x3" => SyntaxTokenType::Float3x3Keyword,
        "float3x4" => SyntaxTokenType::Float3x4Keyword,
        "float4x1" => SyntaxTokenType::Float4x1Keyword,
        "float4x2" => SyntaxTokenType::Float4x2Keyword,
        "float4x3" => SyntaxTokenType::Float4x3Keyword,
        "float4x4" => SyntaxTokenType::Float4x4Keyword,
        "for" => SyntaxTokenType::ForKeyword,
        "globallycoherent" => SyntaxTokenType::GloballycoherentKeyword,
        "groupshared" => SyntaxTokenType::GroupsharedKeyword,
        "half" => SyntaxTokenType::HalfKeyword,
        "half1" => SyntaxTokenType::Half1Keyword,
        "half2" => SyntaxTokenType::Half2Keyword,
        "half3" => SyntaxTokenType::Half3Keyword,
        "half4" => SyntaxTokenType::Half4Keyword,
        "half1x1" => SyntaxTokenType::Half1x1Keyword,
        "half1x2" => SyntaxTokenType::Half1x2Keyword,
        "half1x3" => SyntaxTokenType::Half1x3Keyword,
        "half1x4" => SyntaxTokenType::Half1x4Keyword,
        "half2x1" => SyntaxTokenType::Half2x1Keyword,
        "half2x2" => SyntaxTokenType::Half2x2Keyword,
        "half2x3" => SyntaxTokenType::Half2x3Keyword,
        "half2x4" => SyntaxTokenType::Half2x4Keyword,
        "half3x1" => SyntaxTokenType::Half3x1Keyword,
        "half3x2" => SyntaxTokenType::Half3x2Keyword,
        "half3x3" => SyntaxTokenType::Half3x3Keyword,
        "half3x4" => SyntaxTokenType::Half3x4Keyword,
        "half4x1" => SyntaxTokenType::Half4x1Keyword,
        "half4x2" => SyntaxTokenType::Half4x2Keyword,
        "half4x3" => SyntaxTokenType::Half4x3Keyword,
        "half4x4" => SyntaxTokenType::Half4x4Keyword,
        "float16_t" => SyntaxTokenType::Float16_tKeyword,
        "float16_t1" => SyntaxTokenType::Float16_t1Keyword,
        "float16_t2" => SyntaxTokenType::Float16_t2Keyword,
        "float16_t3" => SyntaxTokenType::Float16_t3Keyword,
        "float16_t4" => SyntaxTokenType::Float16_t4Keyword,
        "float16_t1x1" => SyntaxTokenType::Float16_t1x1Keyword,
        "float16_t1x2" => SyntaxTokenType::Float16_t1x2Keyword,
        "float16_t1x3" => SyntaxTokenType::Float16_t1x3Keyword,
        "float16_t1x4" => SyntaxTokenType::Float16_t1x4Keyword,
        "float16_t2x1" => SyntaxTokenType::Float16_t2x1Keyword,
        "float16_t2x2" => SyntaxTokenType::Float16_t2x2Keyword,
        "float16_t2x3" => SyntaxTokenType::Float16_t2x3Keyword,
        "float16_t2x4" => SyntaxTokenType::Float16_t2x4Keyword,
        "float16_t3x1" => SyntaxTokenType::Float16_t3x1Keyword,
        "float16_t3x2" => SyntaxTokenType::Float16_t3x2Keyword,
        "float16_t3x3" => SyntaxTokenType::Float16_t3x3Keyword,
        "float16_t3x4" => SyntaxTokenType::Float16_t3x4Keyword,
        "float16_t4x1" => SyntaxTokenType::Float16_t4x1Keyword,
        "float16_t4x2" => SyntaxTokenType::Float16_t4x2Keyword,
        "float16_t4x3" => SyntaxTokenType::Float16_t4x3Keyword,
        "float16_t4x4" => SyntaxTokenType::Float16_t4x4Keyword,
        "if" => SyntaxTokenType::IfKeyword,
        "in" => SyntaxTokenType::InKeyword,
        "inline" => SyntaxTokenType::InlineKeyword,
        "inout" => SyntaxTokenType::InoutKeyword,
        "InputPatch" => SyntaxTokenType::InputPatchKeyword,
        "int" => SyntaxTokenType::IntKeyword,
        "int1" => SyntaxTokenType::Int1Keyword,
        "int2" => SyntaxTokenType::Int2Keyword,
        "int3" => SyntaxTokenType::Int3Keyword,
        "int4" => SyntaxTokenType::Int4Keyword,
        "int1x1" => SyntaxTokenType::Int1x1Keyword,
        "int1x2" => SyntaxTokenType::Int1x2Keyword,
        "int1x3" => SyntaxTokenType::Int1x3Keyword,
        "int1x4" => SyntaxTokenType::Int1x4Keyword,
        "int2x1" => SyntaxTokenType::Int2x1Keyword,
        "int2x2" => SyntaxTokenType::Int2x2Keyword,
        "int2x3" => SyntaxTokenType::Int2x3Keyword,
        "int2x4" => SyntaxTokenType::Int2x4Keyword,
        "int3x1" => SyntaxTokenType::Int3x1Keyword,
        "int3x2" => SyntaxTokenType::Int3x2Keyword,
        "int3x3" => SyntaxTokenType::Int3x3Keyword,
        "int3x4" => SyntaxTokenType::Int3x4Keyword,
        "int4x1" => SyntaxTokenType::Int4x1Keyword,
        "int4x2" => SyntaxTokenType::Int4x2Keyword,
        "int4x3" => SyntaxTokenType::Int4x3Keyword,
        "int4x4" => SyntaxTokenType::Int4x4Keyword,
        "int64_t" => SyntaxTokenType::Int64_tKeyword,
        "int64_t1" => SyntaxTokenType::Int64_t1Keyword,
        "int64_t2" => SyntaxTokenType::Int64_t2Keyword,
        "int64_t3" => SyntaxTokenType::Int64_t3Keyword,
        "int64_t4" => SyntaxTokenType::Int64_t4Keyword,
        "int64_t1x1" => SyntaxTokenType::Int64_t1x1Keyword,
        "int64_t1x2" => SyntaxTokenType::Int64_t1x2Keyword,
        "int64_t1x3" => SyntaxTokenType::Int64_t1x3Keyword,
        "int64_t1x4" => SyntaxTokenType::Int64_t1x4Keyword,
        "int64_t2x1" => SyntaxTokenType::Int64_t2x1Keyword,
        "int64_t2x2" => SyntaxTokenType::Int64_t2x2Keyword,
        "int64_t2x3" => SyntaxTokenType::Int64_t2x3Keyword,
        "int64_t2x4" => SyntaxTokenType::Int64_t2x4Keyword,
        "int64_t3x1" => SyntaxTokenType::Int64_t3x1Keyword,
        "int64_t3x2" => SyntaxTokenType::Int64_t3x2Keyword,
        "int64_t3x3" => SyntaxTokenType::Int64_t3x3Keyword,
        "int64_t3x4" => SyntaxTokenType::Int64_t3x4Keyword,
        "int64_t4x1" => SyntaxTokenType::Int64_t4x1Keyword,
        "int64_t4x2" => SyntaxTokenType::Int64_t4x2Keyword,
        "int64_t4x3" => SyntaxTokenType::Int64_t4x3Keyword,
        "int64_t4x4" => SyntaxTokenType::Int64_t4x4Keyword,
        "int16_t" => SyntaxTokenType::Int16_tKeyword,
        "int16_t1" => SyntaxTokenType::Int16_t1Keyword,
        "int16_t2" => SyntaxTokenType::Int16_t2Keyword,
        "int16_t3" => SyntaxTokenType::Int16_t3Keyword,
        "int16_t4" => SyntaxTokenType::Int16_t4Keyword,
        "int16_t1x1" => SyntaxTokenType::Int16_t1x1Keyword,
        "int16_t1x2" => SyntaxTokenType::Int16_t1x2Keyword,
        "int16_t1x3" => SyntaxTokenType::Int16_t1x3Keyword,
        "int16_t1x4" => SyntaxTokenType::Int16_t1x4Keyword,
        "int16_t2x1" => SyntaxTokenType::Int16_t2x1Keyword,
        "int16_t2x2" => SyntaxTokenType::Int16_t2x2Keyword,
        "int16_t2x3" => SyntaxTokenType::Int16_t2x3Keyword,
        "int16_t2x4" => SyntaxTokenType::Int16_t2x4Keyword,
        "int16_t3x1" => SyntaxTokenType::Int16_t3x1Keyword,
        "int16_t3x2" => SyntaxTokenType::Int16_t3x2Keyword,
        "int16_t3x3" => SyntaxTokenType::Int16_t3x3Keyword,
        "int16_t3x4" => SyntaxTokenType::Int16_t3x4Keyword,
        "int16_t4x1" => SyntaxTokenType::Int16_t4x1Keyword,
        "int16_t4x2" => SyntaxTokenType::Int16_t4x2Keyword,
        "int16_t4x3" => SyntaxTokenType::Int16_t4x3Keyword,
        "int16_t4x4" => SyntaxTokenType::Int16_t4x4Keyword,
        "interface" => SyntaxTokenType::InterfaceKeyword,
        "lineadj" => SyntaxTokenType::LineAdjKeyword,
        "linear" => SyntaxTokenType::LinearKeyword,
        "LineStream" => SyntaxTokenType::LineStreamKeyword,
        "Matrix" => SyntaxTokenType::MatrixKeyword,
        "matrix" => SyntaxTokenType::MatrixKeyword,
        "min10float" => SyntaxTokenType::Min10FloatKeyword,
        "min10float1" => SyntaxTokenType::Min10Float1Keyword,
        "min10float2" => SyntaxTokenType::Min10Float2Keyword,
        "min10float3" => SyntaxTokenType::Min10Float3Keyword,
        "min10float4" => SyntaxTokenType::Min10Float4Keyword,
        "min10float1x1" => SyntaxTokenType::Min10Float1x1Keyword,
        "min10float1x2" => SyntaxTokenType::Min10Float1x2Keyword,
        "min10float1x3" => SyntaxTokenType::Min10Float1x3Keyword,
        "min10float1x4" => SyntaxTokenType::Min10Float1x4Keyword,
        "min10float2x1" => SyntaxTokenType::Min10Float2x1Keyword,
        "min10float2x2" => SyntaxTokenType::Min10Float2x2Keyword,
        "min10float2x3" => SyntaxTokenType::Min10Float2x3Keyword,
        "min10float2x4" => SyntaxTokenType::Min10Float2x4Keyword,
        "min10float3x1" => SyntaxTokenType::Min10Float3x1Keyword,
        "min10float3x2" => SyntaxTokenType::Min10Float3x2Keyword,
        "min10float3x3" => SyntaxTokenType::Min10Float3x3Keyword,
        "min10float3x4" => SyntaxTokenType::Min10Float3x4Keyword,
        "min10float4x1" => SyntaxTokenType::Min10Float4x1Keyword,
        "min10float4x2" => SyntaxTokenType::Min10Float4x2Keyword,
        "min10float4x3" => SyntaxTokenType::Min10Float4x3Keyword,
        "min10float4x4" => SyntaxTokenType::Min10Float4x4Keyword,
        "min12int" => SyntaxTokenType::Min12IntKeyword,
        "min12int1" => SyntaxTokenType::Min12Int1Keyword,
        "min12int2" => SyntaxTokenType::Min12Int2Keyword,
        "min12int3" => SyntaxTokenType::Min12Int3Keyword,
        "min12int4" => SyntaxTokenType::Min12Int4Keyword,
        "min12int1x1" => SyntaxTokenType::Min12Int1x1Keyword,
        "min12int1x2" => SyntaxTokenType::Min12Int1x2Keyword,
        "min12int1x3" => SyntaxTokenType::Min12Int1x3Keyword,
        "min12int1x4" => SyntaxTokenType::Min12Int1x4Keyword,
        "min12int2x1" => SyntaxTokenType::Min12Int2x1Keyword,
        "min12int2x2" => SyntaxTokenType::Min12Int2x2Keyword,
        "min12int2x3" => SyntaxTokenType::Min12Int2x3Keyword,
        "min12int2x4" => SyntaxTokenType::Min12Int2x4Keyword,
        "min12int3x1" => SyntaxTokenType::Min12Int3x1Keyword,
        "min12int3x2" => SyntaxTokenType::Min12Int3x2Keyword,
        "min12int3x3" => SyntaxTokenType::Min12Int3x3Keyword,
        "min12int3x4" => SyntaxTokenType::Min12Int3x4Keyword,
        "min12int4x1" => SyntaxTokenType::Min12Int4x1Keyword,
        "min12int4x2" => SyntaxTokenType::Min12Int4x2Keyword,
        "min12int4x3" => SyntaxTokenType::Min12Int4x3Keyword,
        "min12int4x4" => SyntaxTokenType::Min12Int4x4Keyword,
        "min16float" => SyntaxTokenType::Min16FloatKeyword,
        "min16float1" => SyntaxTokenType::Min16Float1Keyword,
        "min16float2" => SyntaxTokenType::Min16Float2Keyword,
        "min16float3" => SyntaxTokenType::Min16Float3Keyword,
        "min16float4" => SyntaxTokenType::Min16Float4Keyword,
        "min16float1x1" => SyntaxTokenType::Min16Float1x1Keyword,
        "min16float1x2" => SyntaxTokenType::Min16Float1x2Keyword,
        "min16float1x3" => SyntaxTokenType::Min16Float1x3Keyword,
        "min16float1x4" => SyntaxTokenType::Min16Float1x4Keyword,
        "min16float2x1" => SyntaxTokenType::Min16Float2x1Keyword,
        "min16float2x2" => SyntaxTokenType::Min16Float2x2Keyword,
        "min16float2x3" => SyntaxTokenType::Min16Float2x3Keyword,
        "min16float2x4" => SyntaxTokenType::Min16Float2x4Keyword,
        "min16float3x1" => SyntaxTokenType::Min16Float3x1Keyword,
        "min16float3x2" => SyntaxTokenType::Min16Float3x2Keyword,
        "min16float3x3" => SyntaxTokenType::Min16Float3x3Keyword,
        "min16float3x4" => SyntaxTokenType::Min16Float3x4Keyword,
        "min16float4x1" => SyntaxTokenType::Min16Float4x1Keyword,
        "min16float4x2" => SyntaxTokenType::Min16Float4x2Keyword,
        "min16float4x3" => SyntaxTokenType::Min16Float4x3Keyword,
        "min16float4x4" => SyntaxTokenType::Min16Float4x4Keyword,
        "min16int" => SyntaxTokenType::Min16IntKeyword,
        "min16int1" => SyntaxTokenType::Min16Int1Keyword,
        "min16int2" => SyntaxTokenType::Min16Int2Keyword,
        "min16int3" => SyntaxTokenType::Min16Int3Keyword,
        "min16int4" => SyntaxTokenType::Min16Int4Keyword,
        "min16int1x1" => SyntaxTokenType::Min16Int1x1Keyword,
        "min16int1x2" => SyntaxTokenType::Min16Int1x2Keyword,
        "min16int1x3" => SyntaxTokenType::Min16Int1x3Keyword,
        "min16int1x4" => SyntaxTokenType::Min16Int1x4Keyword,
        "min16int2x1" => SyntaxTokenType::Min16Int2x1Keyword,
        "min16int2x2" => SyntaxTokenType::Min16Int2x2Keyword,
        "min16int2x3" => SyntaxTokenType::Min16Int2x3Keyword,
        "min16int2x4" => SyntaxTokenType::Min16Int2x4Keyword,
        "min16int3x1" => SyntaxTokenType::Min16Int3x1Keyword,
        "min16int3x2" => SyntaxTokenType::Min16Int3x2Keyword,
        "min16int3x3" => SyntaxTokenType::Min16Int3x3Keyword,
        "min16int3x4" => SyntaxTokenType::Min16Int3x4Keyword,
        "min16int4x1" => SyntaxTokenType::Min16Int4x1Keyword,
        "min16int4x2" => SyntaxTokenType::Min16Int4x2Keyword,
        "min16int4x3" => SyntaxTokenType::Min16Int4x3Keyword,
        "min16int4x4" => SyntaxTokenType::Min16Int4x4Keyword,
        "min16uint" => SyntaxTokenType::Min16UintKeyword,
        "min16uint1" => SyntaxTokenType::Min16Uint1Keyword,
        "min16uint2" => SyntaxTokenType::Min16Uint2Keyword,
        "min16uint3" => SyntaxTokenType::Min16Uint3Keyword,
        "min16uint4" => SyntaxTokenType::Min16Uint4Keyword,
        "min16uint1x1" => SyntaxTokenType::Min16Uint1x1Keyword,
        "min16uint1x2" => SyntaxTokenType::Min16Uint1x2Keyword,
        "min16uint1x3" => SyntaxTokenType::Min16Uint1x3Keyword,
        "min16uint1x4" => SyntaxTokenType::Min16Uint1x4Keyword,
        "min16uint2x1" => SyntaxTokenType::Min16Uint2x1Keyword,
        "min16uint2x2" => SyntaxTokenType::Min16Uint2x2Keyword,
        "min16uint2x3" => SyntaxTokenType::Min16Uint2x3Keyword,
        "min16uint2x4" => SyntaxTokenType::Min16Uint2x4Keyword,
        "min16uint3x1" => SyntaxTokenType::Min16Uint3x1Keyword,
        "min16uint3x2" => SyntaxTokenType::Min16Uint3x2Keyword,
        "min16uint3x3" => SyntaxTokenType::Min16Uint3x3Keyword,
        "min16uint3x4" => SyntaxTokenType::Min16Uint3x4Keyword,
        "min16uint4x1" => SyntaxTokenType::Min16Uint4x1Keyword,
        "min16uint4x2" => SyntaxTokenType::Min16Uint4x2Keyword,
        "min16uint4x3" => SyntaxTokenType::Min16Uint4x3Keyword,
        "min16uint4x4" => SyntaxTokenType::Min16Uint4x4Keyword,
        "namespace" => SyntaxTokenType::NamespaceKeyword,
        "nointerpolation" => SyntaxTokenType::NointerpolationKeyword,
        "noperspective" => SyntaxTokenType::NoperspectiveKeyword,
        "out" => SyntaxTokenType::OutKeyword,
        "OutputPatch" => SyntaxTokenType::OutputPatchKeyword,
        "packoffset" => SyntaxTokenType::PackoffsetKeyword,
        "pass" => SyntaxTokenType::PassKeyword,
        "Pass" => SyntaxTokenType::PassKeyword,
        "point" => SyntaxTokenType::PointKeyword,
        "PointStream" => SyntaxTokenType::PointStreamKeyword,
        "precise" => SyntaxTokenType::PreciseKeyword,
        "RasterizerOrderedBuffer" => SyntaxTokenType::RasterizerOrderedBufferKeyword,
        "RasterizerOrderedByteAddressBuffer" => SyntaxTokenType::RasterizerOrderedByteAddressBufferKeyword,
        "RasterizerOrderedStructuredBuffer" => SyntaxTokenType::RasterizerOrderedStructuredBufferKeyword,
        "RasterizerOrderedTexture1D" => SyntaxTokenType::RasterizerOrderedTexture1DKeyword,
        "RasterizerOrderedTexture1DArray" => SyntaxTokenType::RasterizerOrderedTexture1DArrayKeyword,
        "RasterizerOrderedTexture2D" => SyntaxTokenType::RasterizerOrderedTexture2DKeyword,
        "RasterizerOrderedTexture2DArray" => SyntaxTokenType::RasterizerOrderedTexture2DArrayKeyword,
        "RasterizerOrderedTexture3D" => SyntaxTokenType::RasterizerOrderedTexture3DKeyword,
        "RasterizerState" => SyntaxTokenType::RasterizerStateKeyword,
        "register" => SyntaxTokenType::RegisterKeyword,
        "return" => SyntaxTokenType::ReturnKeyword,
        "row_major" => SyntaxTokenType::RowMajorKeyword,
        "RWBuffer" => SyntaxTokenType::RWBufferKeyword,
        "RWByteAddressBuffer" => SyntaxTokenType::RWByteAddressBufferKeyword,
        "RWStructuredBuffer" => SyntaxTokenType::RWStructuredBufferKeyword,
        "RWTexture1D" => SyntaxTokenType::RWTexture1DKeyword,
        "RWTexture1DArray" => SyntaxTokenType::RWTexture1DArrayKeyword,
        "RWTexture2D" => SyntaxTokenType::RWTexture2DKeyword,
        "RWTexture2DArray" => SyntaxTokenType::RWTexture2DArrayKeyword,
        "RWTexture3D" => SyntaxTokenType::RWTexture3DKeyword,
        "sampler" => SyntaxTokenType::SamplerKeyword,
        "sampler1D" => SyntaxTokenType::Sampler1DKeyword,
        "sampler2D" => SyntaxTokenType::Sampler2DKeyword,
        "sampler3D" => SyntaxTokenType::Sampler3DKeyword,
        "samplerCUBE" => SyntaxTokenType::SamplerCubeKeyword,
        "SamplerComparisonState" => SyntaxTokenType::SamplerComparisonStateKeyword,
        "SamplerState" => SyntaxTokenType::SamplerStateKeyword,
        "sampler_state" => SyntaxTokenType::SamplerStateLegacyKeyword,
        "shared" => SyntaxTokenType::SharedKeyword,
        "snorm" => SyntaxTokenType::SNormKeyword,
        "static" => SyntaxTokenType::StaticKeyword,
        "string" => SyntaxTokenType::StringKeyword,
        "struct" => SyntaxTokenType::StructKeyword,
        "StructuredBuffer" => SyntaxTokenType::StructuredBufferKeyword,
        "switch" => SyntaxTokenType::SwitchKeyword,
        "tbuffer" => SyntaxTokenType::TBufferKeyword,
        "technique" => SyntaxTokenType::TechniqueKeyword,
        "Technique" => SyntaxTokenType::TechniqueKeyword,
        "technique10" => SyntaxTokenType::Technique10Keyword,
        "technique11" => SyntaxTokenType::Technique11Keyword,
        "texture2D" => SyntaxTokenType::Texture2DLegacyKeyword,
        "textureCUBE" => SyntaxTokenType::TextureCubeLegacyKeyword,
        "Texture1D" => SyntaxTokenType::Texture1DKeyword,
        "Texture1DArray" => SyntaxTokenType::Texture1DArrayKeyword,
        "Texture2D" => SyntaxTokenType::Texture2DKeyword,
        "Texture2DArray" => SyntaxTokenType::Texture2DArrayKeyword,
        "Texture2DMS" => SyntaxTokenType::Texture2DMSKeyword,
        "Texture2DMSArray" => SyntaxTokenType::Texture2DMSArrayKeyword,
        "Texture3D" => SyntaxTokenType::Texture3DKeyword,
        "TextureCube" => SyntaxTokenType::TextureCubeKeyword,
        "TextureCubeArray" => SyntaxTokenType::TextureCubeArrayKeyword,
        "triangle" => SyntaxTokenType::TriangleKeyword,
        "triangleadj" => SyntaxTokenType::TriangleAdjKeyword,
        "TriangleStream" => SyntaxTokenType::TriangleStreamKeyword,
        "typedef" => SyntaxTokenType::TypedefKeyword,
        "uniform" => SyntaxTokenType::UniformKeyword,
        "unorm" => SyntaxTokenType::UNormKeyword,
        "unsigned" => SyntaxTokenType::UnsignedKeyword,
        "uint" => SyntaxTokenType::UintKeyword,
        "dword" => SyntaxTokenType::DwordKeyword,
        "uint1" => SyntaxTokenType::Uint1Keyword,
        "uint2" => SyntaxTokenType::Uint2Keyword,
        "uint3" => SyntaxTokenType::Uint3Keyword,
        "uint4" => SyntaxTokenType::Uint4Keyword,
        "uint1x1" => SyntaxTokenType::Uint1x1Keyword,
        "uint1x2" => SyntaxTokenType::Uint1x2Keyword,
        "uint1x3" => SyntaxTokenType::Uint1x3Keyword,
        "uint1x4" => SyntaxTokenType::Uint1x4Keyword,
        "uint2x1" => SyntaxTokenType::Uint2x1Keyword,
        "uint2x2" => SyntaxTokenType::Uint2x2Keyword,
        "uint2x3" => SyntaxTokenType::Uint2x3Keyword,
        "uint2x4" => SyntaxTokenType::Uint2x4Keyword,
        "uint3x1" => SyntaxTokenType::Uint3x1Keyword,
        "uint3x2" => SyntaxTokenType::Uint3x2Keyword,
        "uint3x3" => SyntaxTokenType::Uint3x3Keyword,
        "uint3x4" => SyntaxTokenType::Uint3x4Keyword,
        "uint4x1" => SyntaxTokenType::Uint4x1Keyword,
        "uint4x2" => SyntaxTokenType::Uint4x2Keyword,
        "uint4x3" => SyntaxTokenType::Uint4x3Keyword,
        "uint4x4" => SyntaxTokenType::Uint4x4Keyword,
        "uint64_t" => SyntaxTokenType::Uint64_tKeyword,
        "uint64_t1" => SyntaxTokenType::Uint64_t1Keyword,
        "uint64_t2" => SyntaxTokenType::Uint64_t2Keyword,
        "uint64_t3" => SyntaxTokenType::Uint64_t3Keyword,
        "uint64_t4" => SyntaxTokenType::Uint64_t4Keyword,
        "uint64_t1x1" => SyntaxTokenType::Uint64_t1x1Keyword,
        "uint64_t1x2" => SyntaxTokenType::Uint64_t1x2Keyword,
        "uint64_t1x3" => SyntaxTokenType::Uint64_t1x3Keyword,
        "uint64_t1x4" => SyntaxTokenType::Uint64_t1x4Keyword,
        "uint64_t2x1" => SyntaxTokenType::Uint64_t2x1Keyword,
        "uint64_t2x2" => SyntaxTokenType::Uint64_t2x2Keyword,
        "uint64_t2x3" => SyntaxTokenType::Uint64_t2x3Keyword,
        "uint64_t2x4" => SyntaxTokenType::Uint64_t2x4Keyword,
        "uint64_t3x1" => SyntaxTokenType::Uint64_t3x1Keyword,
        "uint64_t3x2" => SyntaxTokenType::Uint64_t3x2Keyword,
        "uint64_t3x3" => SyntaxTokenType::Uint64_t3x3Keyword,
        "uint64_t3x4" => SyntaxTokenType::Uint64_t3x4Keyword,
        "uint64_t4x1" => SyntaxTokenType::Uint64_t4x1Keyword,
        "uint64_t4x2" => SyntaxTokenType::Uint64_t4x2Keyword,
        "uint64_t4x3" => SyntaxTokenType::Uint64_t4x3Keyword,
        "uint64_t4x4" => SyntaxTokenType::Uint64_t4x4Keyword,
        "uint16_t" => SyntaxTokenType::Uint16_tKeyword,
        "uint16_t1" => SyntaxTokenType::Uint16_t1Keyword,
        "uint16_t2" => SyntaxTokenType::Uint16_t2Keyword,
        "uint16_t3" => SyntaxTokenType::Uint16_t3Keyword,
        "uint16_t4" => SyntaxTokenType::Uint16_t4Keyword,
        "uint16_t1x1" => SyntaxTokenType::Uint16_t1x1Keyword,
        "uint16_t1x2" => SyntaxTokenType::Uint16_t1x2Keyword,
        "uint16_t1x3" => SyntaxTokenType::Uint16_t1x3Keyword,
        "uint16_t1x4" => SyntaxTokenType::Uint16_t1x4Keyword,
        "uint16_t2x1" => SyntaxTokenType::Uint16_t2x1Keyword,
        "uint16_t2x2" => SyntaxTokenType::Uint16_t2x2Keyword,
        "uint16_t2x3" => SyntaxTokenType::Uint16_t2x3Keyword,
        "uint16_t2x4" => SyntaxTokenType::Uint16_t2x4Keyword,
        "uint16_t3x1" => SyntaxTokenType::Uint16_t3x1Keyword,
        "uint16_t3x2" => SyntaxTokenType::Uint16_t3x2Keyword,
        "uint16_t3x3" => SyntaxTokenType::Uint16_t3x3Keyword,
        "uint16_t3x4" => SyntaxTokenType::Uint16_t3x4Keyword,
        "uint16_t4x1" => SyntaxTokenType::Uint16_t4x1Keyword,
        "uint16_t4x2" => SyntaxTokenType::Uint16_t4x2Keyword,
        "uint16_t4x3" => SyntaxTokenType::Uint16_t4x3Keyword,
        "uint16_t4x4" => SyntaxTokenType::Uint16_t4x4Keyword,
        "vector" => SyntaxTokenType::VectorKeyword,
        "volatile" => SyntaxTokenType::VolatileKeyword,
        "void" => SyntaxTokenType::VoidKeyword,
        "while" => SyntaxTokenType::WhileKeyword,
        "false" => SyntaxTokenType::FalseKeyword,
        "true" => SyntaxTokenType::TrueKeyword,
        _ => SyntaxTokenType::IdentifierToken,
    }
}

#[derive(Default, Clone, Debug)]
pub struct SyntaxToken {
    // needs type, reference to file, line, range of text etc..
    pub token_type: SyntaxTokenType,
}

impl fmt::Display for SyntaxToken
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}
